apiVersion: apps/v1
kind: Deployment
metadata:
  name: drdcyudyt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drdcyudyt
  template:
    metadata:
      labels:
        app: drdcyudyt
    spec:
      containers:
      - image: okteto.dev/drdcyudyt:latest
        name: drdcyudyt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "3bf6c5b4-9697-23c0-98d3-8f531f1945f2"
        - name: Vless_Path
          value: "/vlvhgv555"
        - name: Vmess_UUID
          value: "3bf6c5b4-9697-23c0-98d3-8f531f1945f2"
        - name: Vmess_Path
          value: "/vmrgd666"
        - name: Share_Path
          value: "/v2link"
